[Interface]
Address = 10.200.0.1/24
ListenPort = 51820
PrivateKey = GGhm8ELlCokN53y/Og/tkKGrhaK4eHX8ThC31YqV+nY=
 
[Peer]
PublicKey = iXOvNNxUhPbisWKEHZAqScFatiuEDUJZkgXyRZQm4CI=
AllowedIPs = 10.200.0.2/32